// this component is generated by the camera system and should not be added manually to entities

export interface CameraComputedComponent {
  viewMatrix: Float32Array; // The view matrix representing the camera's position and orientation in the world
  projectionMatrix: Float32Array; // The projection matrix representing the camera's perspective or orthographic projection parameters
  viewProjectionMatrix: Float32Array; // The combined view-projection matrix used for rendering, calculated as projectionMatrix * viewMatrix
}